import ClientNotesProvider from "./components/ClientNotesProvider";
import { Inconsolata } from "next/font/google";
import "./globals.css";

const inconsolata = Inconsolata({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inconsolata.className}>
        {" "}
        <ClientNotesProvider>{children}</ClientNotesProvider>
      </body>
    </html>
  );
}
